Repository darkard2003/cubeXtimerKotlin, pull requests merged in 2024-01, with the labels that each got.

#6 Enhance History UI
  app/src/main/java/com/example/dark_x_timer_kotlin/ui/counter/historySheet/HIstorySheetUI.kt
Labels: apertre, medium

#7 Implement Delete Feature
  app/src/main/java/com/example/dark_x_timer_kotlin/ui/counter/historySheet/HIstorySheetUI.kt
  app/src/main/java/com/example/dark_x_timer_kotlin/ui/counter/historySheet/HistoryViewModel.kt
Labels: apertre, easy

#8 feat: Add Delete Record Confirmation Dialog
  app/src/main/java/com/example/dark_x_timer_kotlin/ui/AppViewModelProvider.kt
  app/src/main/java/com/example/dark_x_timer_kotlin/ui/counter/deleteDialog/DeleteDialog.kt
  app/src/main/java/com/example/dark_x_timer_kotlin/ui/counter/deleteDialog/DeleteUIState.kt
  app/src/main/java/com/example/dark_x_timer_kotlin/ui/counter/deleteDialog/DeleteViewModel.kt
  app/src/main/java/com/example/dark_x_timer_kotlin/ui/counter/historySheet/HIstorySheetUI.kt
  app/src/main/java/com/example/dark_x_timer_kotlin/ui/counter/historySheet/HistorySheetState.kt
  app/src/main/java/com/example/dark_x_timer_kotlin/ui/counter/historySheet/HistoryViewModel.kt
Labels: apertre, hard

#11 feat: Filter History based on Cube Type
  app/src/main/java/com/example/dark_x_timer_kotlin/ui/counter/historySheet/HIstorySheetUI.kt
  app/src/main/java/com/example/dark_x_timer_kotlin/ui/counter/historySheet/HistorySheetState.kt
  app/src/main/java/com/example/dark_x_timer_kotlin/ui/counter/historySheet/HistoryViewModel.kt
Labels: apertre, hard

#12 Fix: Record name default to "Untitled"
  app/src/main/java/com/example/dark_x_timer_kotlin/ui/counter/saveDialog/SaveViewModel.kt
Labels: apertre, easy

#13 feat: Average and Best Time Indicators
  app/src/main/java/com/example/dark_x_timer_kotlin/ui/counter/historySheet/HIstorySheetUI.kt
  app/src/main/java/com/example/dark_x_timer_kotlin/ui/counter/historySheet/HistoryViewModel.kt
Labels: apertre, hard

#15 feat: Informational messages when saving record
  app/src/main/java/com/example/dark_x_timer_kotlin/ui/counter/saveDialog/SaveDialog.kt
  app/src/main/java/com/example/dark_x_timer_kotlin/ui/counter/saveDialog/SaveMessages.kt
  app/src/main/java/com/example/dark_x_timer_kotlin/ui/counter/saveDialog/SaveViewModel.kt
Labels: apertre, medium

#21 Set up GitHub Actions workflow to build the app on push and PRs
  .github/workflows/build-app.yml
Labels: apertre, medium

#22 Update README.md
  README.md
Labels: apertre, medium
